name: Publish MY.CorrelationId

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.301

        - name: Install dependencies
          run: dotnet restore src/dotnet/MY.CorrelationId.sln

        - name: Build
          run: dotnet build src/dotnet/MY.CorrelationId.sln --configuration Release --no-restore

        - name: Publish MY.CorrelationId
          uses: brandedoutcast/publish-nuget@v2.5.2
          with:
            PROJECT_FILE_PATH: src/dotnet/MY.CorrelationId/MY.CorrelationId.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
            NUGET_SOURCE: https://api.nuget.org

        - name: Publish My.CorrelationId.Serilog
          uses: brandedoutcast/publish-nuget@v2.5.2
          with:
            PROJECT_FILE_PATH: src/dotnet/My.CorrelationId.Serilog/My.CorrelationId.Serilog.csproj
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
            NUGET_SOURCE: https://api.nuget.org
